API_CONFIG:
  limit: 1000000
AUTH:
  username: chlynch0
  password: W#llie7360000
  auth-header: Basic Y2hseW5jaDpXI2xsaWU3MzYwMA==00
  cookie: AWSALB=ITtwYN2XhZe79p5QG2kgvZBRnWYjzaHsNbwhnoT0Y4PGLu69X//WO/sZjtET2v5Aeml1NEG/O499U1IcelGQYzOTT1cxSVqYlRkJCJE9mIT68JEXneaVqcMPZEHV; AWSALBCORS=ITtwYN2XhZe79p5QG2kgvZBRnWYjzaHsNbwhnoT0Y4PGLu69X//WO/sZjtET2v5Aeml1NEG/O499U1IcelGQYzOTT1cxSVqYlRkJCJE9mIT68JEXneaVqcMPZEHV; JSESSIONID=09599047-3630-435b-80d7-26e27533365e
  token_auth_header: Basic Z2VuX2NvbGxpYnJhX2FwaXVzZXI6QlFiNHk1c3dNczdEcFlRRGlNTTVNSGlpcHJnaHZBN0dHcTY2bnBLYWZaZlYxd0t0SG44S2V2S29zVU5Fb0hJNg==
ENVIRONMENT:
  gore: wlgore-dev.collibra.com
MYSQL_CONNECTION_DETAILS:
  SERVER_NAME: anvrdmexldv03
  DATABASE_NAME: CollibraMetrics
  LOGIN: CollibraDev
  PASSWORD: EXLCollibra@123456
  SQL_QUERY: >
   select  [SN_System_ID], sn_assets.[Name] asset_name,  [CI_Number],[Install_Status],
   [Business_Criticality] ,[URL],[Owned_By],[IT_Owner],[Supported_By],[Regulatory_And_Compliance_Standards],
   [Export_Control],[Legal_Hold],[APM_Data_Sensitivity],[Disaster_Recovery_Gap],[Records_Retention]
              from Extract.servicenow_cmbd_ci_service_discovered_raw sn_assets left Join
            (select * from collibra.collibra_assets where is_current=1 and
            Domain_ID ='ba4a4398-1ced-40ed-9869-d463bc6ccf53') collibra_assets on sn_assets.Name =
            collibra_assets.name where collibra_assets.Name is null
  VARCHAR_LENGTH: 8000
COLLIBRA_DETAILS:
  ADMIN_DOMAIN_ID: 1df968dc-1be2-4c16-af33-59f59fd5858b
  asset_name: b7023ae-9baf-4012-b6f2-aa52483d6c46
  CI_Number: dda874d3-610e-4460-b4d1-7ef304605392
  Install_Status: 8eeeae37-e6cc-4cd9-a65d-c5b6c3a72c36
  Business_Criticality: 12d0118b-6d7b-4ef2-86aa-a44b5552dad9
  URL: 00000000-0000-0000-0000-000000000258
  Owned_By: eff75d33-cba0-44d8-9c2a-f4c3fc589693
  IT_Owner: 23c90dd8-eba5-4a0b-8d2e-98ef071963c8
  Supported_By: 42203189-d926-4fb6-b809-829e9596bc28
  Export_Control: 5acb934c-e521-4858-8732-bffa326419ea
  Legal_Hold: 8100009a-2a8d-4dfa-9b83-77e65534318c
  APM_Data_Sensitivity: 270d4a3d-fd4e-45b8-b2bc-57b0bc31b12d
  Disaster_Recovery_Gap: c6b1b435-956e-4cf7-b675-62287cb99f6e
  Records_Retention: 42024702-5654-4b3b-9bb9-2de6e806882e
SERVICE_NOW:
  ENVIRONMENT: goredev
  USERNAME: CollibraServiceNow
  PASSWORD: 5ee8a5351b26c5d0973dfd115b4bcb2e
  CLIENT_ID: af3129f57162c5d0dd53edce09920e9a
  CLIENT_SECRET: kWG**2P-%24K
  COOKIE: BIGipServerpool_goredev=a9e38fd365549b0c2c33897783bb1723; JSESSIONID=5BE2DB2FFD81BD35C9CB7A3F4CB3523C; glide_user_activity=U0N2M18xOmF3WElJdWl2VmxKWm4vUE5ZdGtEdVExNmpuU2ZWR0I5Z2dyQjFsbk9BckE9Om5HMitOZ1lxMXV1SWVDZXpYaWlXdWdMd3Fxb2czZWdmTTFYb3FEdXBqV2M9; glide_user_route=glide.c2430e9397ea43e166882ffdb6b97fa1
LOGGER:
  LOCATION: log
